spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwer12#$
    url : jdbc:mysql://localhost:3306/community?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8

